steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$BUILD_ID
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - --build-arg
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - --build-arg
      - NEXT_PUBLIC_BASE_URL=${_NEXT_PUBLIC_BASE_URL}
      - --build-arg
      - NEXT_PUBLIC_AWS_REGION=${_NEXT_PUBLIC_AWS_REGION}
      - --build-arg
      - NEXT_PUBLIC_AWS_S3_BUCKET_NAME=${_NEXT_PUBLIC_AWS_S3_BUCKET_NAME}
      - --build-arg
      - NEXT_PUBLIC_AWS_S3_URL=${_NEXT_PUBLIC_AWS_S3_URL}
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_STORAGE_BUCKET=${_NEXT_PUBLIC_SUPABASE_STORAGE_BUCKET}
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$BUILD_ID

substitutions:
  _REGION: europe-west1
  _REPOSITORY: lbc-images
  _IMAGE: lbc-web
  _NEXT_PUBLIC_SUPABASE_URL: ''
  _NEXT_PUBLIC_SUPABASE_ANON_KEY: ''
  _NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ''
  _NEXT_PUBLIC_BASE_URL: ''
  _NEXT_PUBLIC_AWS_REGION: ''
  _NEXT_PUBLIC_AWS_S3_BUCKET_NAME: ''
  _NEXT_PUBLIC_AWS_S3_URL: ''
  _NEXT_PUBLIC_SUPABASE_STORAGE_BUCKET: ''

options:
  logging: CLOUD_LOGGING_ONLY
